response_dict = {
	'akshayd31': ['ey chikna'],
	'mintuj': ['Mintu bol raha hai'],
	'Ashblaze': ['Yo.'],
	'Kevin Abraham': ['nya nya!'],
	'kuro': ['Hands up!'],
	'Übermensch': ['U?'],
	'rishirajatroy': ['U?'],
	'DjentleMonK': ['Yes, I recommend you get rid of RhythmBot.'],
	'jakrukuttan': ['I recommend you cease your extrapolation.'],
	'naveenjohn94': ['🙌'],
	'seldombark': ['the fat one sends his regards.'],
	'pøgbaJr': ['I can verify no bananas were stolen.'],
	'areafunds20': ['Well, well... If it ain\'t Fabulous Fuf!'],
	'mukund': ['RAAAAAAAUUUUUUUUULLL!!!'],
}